name: Truffle Security Secrets Scanner

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Secret Scanning
      id: trufflehog
      uses: trufflesecurity/trufflehog@main
      with:
        extra_args: --only-verified 
        command: trufflehog --path . --sarif --output ./trufflehog-secrets.sarif
      continue-on-error: true
      env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN_2 }}
      
       #--sarif-file-output=trufflehog-secrets.sarif
    
    - name: Upload result to GitHub Code Scanning
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: trufflehog-secrets.sarif

    - name: Monitor secrets with Snyk
      uses: trufflesecurity/trufflehog@main
      with: 
          command: monitor
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN_2 }}  # Use the Snyk Auth Token
      continue-on-error: true

 