name: Truffle Security Secrets Scanner

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: TruffhleHog Secret Scanning
      id: trufflehog
      uses: trufflesecurity/trufflehog@main
      with:
        extra_args: --only-verified
        output: trufflehog-secrets.sarif
      continue-on-error: true
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN_2 }}

    - name: Upload result to GitHub Code Scanning
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: trufflehog-secrets.sarif


   # - name: Save TruffleHog Output
   #   run: echo "${{ steps.trufflehog.outputs.json }}" > trufflehog-secrets.json

    #- name: List files
     # run: ls -al  # Check if the script is in the expected location

    #- name: Print TruffleHog Output
     # run: cat trufflehog-secrets.json

    #- name: Install Snyk CLI
     # run: npm install -g snyk 


    - name: Monitor TruffleHog identified secrets with Snyk
      #uses: trufflesecurity/trufflehog@main
      uses: snyk/actions/node@master
      with: 
          command: monitor #--all-projects --json-file=trufflehog-secrets.json
          output: trufflehog-secrets.sarif
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN_2 }}  
      continue-on-error: true

    
   # - name: Upload TruffleHog JSON file
   #   uses: actions/upload-artifact@v4
    #  with:
     #   name: trufflehog-json
      #  path: trufflehog-secrets.json


   # - name: Total Secrets Found
    #  run: |
     #     length=$(cat trufflehog-secrets.json | jq '.results | length')
      #    echo "RESULTS_LENGTH_2=$length" >> $GITHUB_ENV

    #- name: Send TruffleHog Secrets notification on Slack using Webhooks
     # uses: slackapi/slack-github-action@v1.24.0
      #if: always()
     # with:
      #  payload: |
       #   {
        #    "text": "*The Snyk & TruffleHog Secrets scan result for repo nodejs-goof-BC is : ${{ job.status }}* \n*Number of vulnerabilities : ${{ env.RESULTS_LENGTH_2 }}* \n*Detail*: https://github.com/${{github.repository}}/actions/run/${{github.run_id}}"
         #   }
     # env:
      #  SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}  

#With Enterprise Plan
    - name: Send results to Snyk
      run: |
        curl -X POST "https://snyk.io/api/v1/test" \
        -H "Authorization: token ${{ secrets.SNYK_TOKEN_2 }}" \
        -H "Content-Type: application/json" \
        #-d @trufflehog-secrets.json
      continue-on-error: true 



    



#RUN TS SCANNER
#ADD IN SNYK TEST 
#CONVERT FINDINGS TO SARIF
#UPLOAD TO GIHUB
#SEND TO SNYK