name: Truffle Security Secrets Scanner

on:
  push:
    branches:
      - main
  pull_request:

permissions: 
  contents: read 
  id-token: write 
  issues: write 
  pull-requests: write


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Secret Scanning
      uses: trufflesecurity/trufflehog@main
      with:
        extra_args: --only-verified

        
    - name: Handle Found Secrets
      if: steps.truffle_scan.outputs.secrets_found == 'true'
      run: |
        echo "Secrets found! Please review the logs and take necessary actions."
        # Here you could add commands to notify a team, create an issue, etc.
        
    - name: Notify Team
      if: steps.truffle_scan.outputs.secrets_found == 'true'
      uses: some-notification-action@v1
      with:
        message: "Secrets were detected in the latest commit. Please investigate."




