name: Truffle Security Secrets Scanner

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: TruffhleHog Secret Scanning
      id: trufflehog
      uses: trufflesecurity/trufflehog@main
      with:
        extra_args: --only-verified--json
        #output: trufflehog-secrets.sarif
      continue-on-error: true
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN_2 }}

    - name: Save TruffleHog Output
      run: echo "${{ steps.trufflehog.outputs.json }}" > trufflehog-secrets.json

    - name: List files
      run: ls -al  


    #- name: Install Snyk CLI
     # run: npm install -g snyk 


    - name: Monitor TruffleHog identified secrets with Snyk
      uses: trufflesecurity/trufflehog@main
      #uses: snyk/actions/node@master
      with: 
          command: monitor --all-projects --json-file=trufflehog-secrets.json
          #output: trufflehog-secrets.sarif
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN_2 }}  
      continue-on-error: true

    
    - name: Upload TruffleHog JSON file
      uses: actions/upload-artifact@v4
      with:
        name: trufflehog-json
        path: trufflehog-secrets.json


#With Enterprise Plan
    - name: Send results to Snyk
      run: |
        curl -X POST "https://snyk.io/api/v1/test" \
        -H "Authorization: token ${{ secrets.SNYK_TOKEN_2 }}" \
        -H "Content-Type: application/json" \
        #-d @trufflehog-secrets.json
      continue-on-error: true 



  