name: Truffle Security Secrets Scanner

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Secret Scanning
      id: trufflehog
      uses: trufflesecurity/trufflehog@main
      with:
        extra_args: --only-verified 
        output: trufflehog-secrets.json
      continue-on-error: true
      env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN_2 }}

    - name: Monitor secrets with Snyk
      uses: trufflesecurity/trufflehog@main
      #with: 
          #command: monitor
      with:   
          command: monitor --all-sub-projects --json-file=trufflehog-secrets.json
          #output: trufflehog-secrets.sarif
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN_2 }}  # Use the Snyk Auth Token
      continue-on-error: true
      
       #--sarif-file-output=trufflehog-secrets.sarif

    #- name: List Files
    #  run: ls -al

    #- name: Upload SARIF Report
    #  uses: actions/upload-artifact@v3
     # with:
     #   name: trufflehog-secrets
      #  path: ./trufflehog-secrets.sarif
    
    #- name: Upload result to GitHub Code Scanning
     # uses: github/codeql-action/upload-sarif@v2
     # with:
      #  sarif_file: ./trufflehog-secrets.sarif

  

 