name: Truffle Security Secrets Scanner and GitHub Secret Scanning

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Secret Scanning with TruffleHog
        id: trufflehog
        uses: trufflesecurity/trufflehog@main
        with:
          extra_args: --only-verified
        continue-on-error: true

      - name: Get GitHub Secret Scanning Results
        id: secret_scanning
        run: |
          secrets=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/${{ github.repository }}/secret-scanning/alerts")

          echo "Secrets found: $secrets"
          echo "::set-output name=report::$secrets"

      - name: Combine Findings
        id: combine_findings
        run: |
          trufflehog_report="${{ steps.trufflehog.outputs.report }}"
          github_secrets="${{ steps.secret_scanning.outputs.report }}"

          # Combine the findings into a single JSON array
          combined_payload=$(echo "$trufflehog_report" "$github_secrets" | jq -s '[.[][]]')

          # Check the combined payload
          echo "Combined Snyk Payload: $combined_payload"
          echo "::set-output name=combined_payload::$combined_payload"

      - name: Send Findings to Snyk
        run: |
          combined_payload="${{ steps.combine_findings.outputs.combined_payload }}"

          if [ "$combined_payload" != "[]" ]; then
            response=$(curl -X POST \
              -H "Authorization: token ${{ secrets.SNYK_TOKEN }}" \
              -H "Content-Type: application/json" \
              -d "{\"issues\": $combined_payload}" \
              "https://snyk.io/api/v1/test")

            echo "Snyk API Response: $response"
          else
            echo "No findings to send to Snyk."
          fi











        

