name: Truffle Security Secrets Scanner

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  secrets-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16' # Use a compatible version

      - name: Install Truffle and Truffle Security
        run: |
          npm install -g truffle
          npm install -g truffle-security

      - name: Create temporary truffle-config.js
        run: |
          echo "module.exports = { networks: { development: { host: '127.0.0.1', port: 7545, network_id: '*' } }, compilers: { solc: { version: '0.8.0' } } };" > truffle-config.js

      - name: Run Secrets Scanner
        run: truffle run truffle-security






