name: Truffle Security Secrets Scanner

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: TruffhleHog Secret Scanning
      id: trufflehog
      uses: trufflesecurity/trufflehog@main
      with:
        extra_args: --only-verified 
      continue-on-error: true
     

    - name: Authenticate Snyk
      uses: snyk/actions/node@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN_2 }}
      with:
        command: auth
      continue-on-error: true


    - name: Monitor TruffleHog identified secrets with Snyk
      uses: snyk/actions/node@master 
      with: 
          command: monitor 
      continue-on-error: true


#With Enterprise Plan
    - name: Send results to Snyk
      run: |
        curl --request GET \
        --url "https://api.snyk.io/rest/orgs/{ORG_ID}/projects?version=2024-06-10" \
        --header "Content-Type: application/vnd.api+json" \
        --header "Authorization: token API_TOKEN"
      continue-on-error: true 



  