name: Truffle Security Secrets Scanner

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Secret Scanning
        id: trufflehog
        run: |
          mkdir -p trufflehog_output
          trufflehog --only-verified --json . > trufflehog_output/report.json || echo "TruffleHog scan failed"
          
      - name: Check TruffleHog Output
        run: |
          echo "Raw TruffleHog output:"
          cat trufflehog_output/report.json

      - name: Send TruffleHog findings to Snyk
        run: |
          report=$(cat trufflehog_output/report.json)
          snyk_payload=$(echo "$report" | jq '[.[] | { id: .path, title: .issue, severity: .severity, description: .reason }]')

          # Check the snyk_payload
          echo "Snyk Payload: $snyk_payload"

          if [ "$snyk_payload" != "[]" ]; then
            response=$(curl -X POST \
              -H "Authorization: token ${{ secrets.SNYK_TOKEN }}" \
              -H "Content-Type: application/json" \
              -d "{\"issues\": $snyk_payload}" \
              "https://snyk.io/api/v1/test")

            echo "Snyk API Response: $response"
          else
            echo "No findings to send to Snyk."
          fi








        

